/**
 * The lucide component behind each PinIcon key.
 *
 * Split out of PinEditor.tsx: a component file that also exports a plain
 * constant breaks Fast Refresh (oxlint's react(only-export-components)),
 * and MapPinBar needs this same lookup to draw a pin's icon in the hotbar,
 * not just PinEditor's picker.
 */
import {
  Home,
  Landmark,
  Coins,
  HeartPulse,
  Shield,
  ShoppingBag,
  Backpack,
  Sword,
  Swords,
  Users,
  Tent,
  Flag,
  Skull,
  Ghost,
  Sprout,
  MapPin as MapPinIcon,
  Castle,
  Anvil,
  Hammer,
  Axe,
  FlaskConical,
  Gem,
  KeyRound,
  Lock,
  Star,
  Compass,
  Footprints,
  Flame,
  Droplet,
  Snowflake,
  Mountain,
  TreePine,
  Bird,
  Fish,
  Bug,
  Crown,
  Hourglass,
  ScrollText,
  BookOpen,
  Package,
  Gift,
  PawPrint,
  Wand2,
  Scale,
  Target,
  Anchor,
  Waves,
  Sun,
  Moon,
  Sparkles,
  type LucideIcon,
} from 'lucide-react'
import type { PinIcon } from './mapPins'

export const PIN_ICON_COMPONENT: Record<PinIcon, LucideIcon> = {
  home: Home,
  landmark: Landmark,
  coins: Coins,
  'heart-pulse': HeartPulse,
  shield: Shield,
  'shopping-bag': ShoppingBag,
  backpack: Backpack,
  sword: Sword,
  swords: Swords,
  users: Users,
  tent: Tent,
  flag: Flag,
  skull: Skull,
  ghost: Ghost,
  sprout: Sprout,
  'map-pin': MapPinIcon,
  castle: Castle,
  anvil: Anvil,
  hammer: Hammer,
  axe: Axe,
  'flask-conical': FlaskConical,
  gem: Gem,
  'key-round': KeyRound,
  lock: Lock,
  star: Star,
  compass: Compass,
  footprints: Footprints,
  flame: Flame,
  droplet: Droplet,
  snowflake: Snowflake,
  mountain: Mountain,
  'tree-pine': TreePine,
  bird: Bird,
  fish: Fish,
  bug: Bug,
  crown: Crown,
  hourglass: Hourglass,
  'scroll-text': ScrollText,
  'book-open': BookOpen,
  package: Package,
  gift: Gift,
  'paw-print': PawPrint,
  wand: Wand2,
  scale: Scale,
  target: Target,
  anchor: Anchor,
  waves: Waves,
  sun: Sun,
  moon: Moon,
  sparkles: Sparkles,
}
