/**
 * The lucide component behind each PinIcon key.
 *
 * Split out of PinEditor.tsx: a component file that also exports a plain
 * constant breaks Fast Refresh (oxlint's react(only-export-components)),
 * and MapPinBar needs this same lookup to draw a pin's icon in the hotbar,
 * not just PinEditor's picker.
 *
 * Regenerated in one pass from PIN_ICONS (mapPins.ts) rather than
 * hand-maintained entry by entry, 30 Aug 2026 - at 372 icons, typing this
 * import list and this mapping by hand is exactly the kind of place a typo
 * hides. The `Record<PinIcon, LucideIcon>` type below is what actually
 * catches one: TypeScript will not compile if a PIN_ICONS key here has no
 * matching import, or an import here is never used - see mapPins.ts's own
 * comment for how PIN_ICONS itself was checked against the installed
 * package before any of these names were trusted.
 */
import {
  AlertTriangle,
  Amphora,
  Anchor,
  Angry,
  Annoyed,
  Anvil,
  Archive,
  ArchiveRestore,
  Armchair,
  Atom,
  Award,
  Axe,
  Baby,
  Backpack,
  Banana,
  Bath,
  Beaker,
  Bean,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  Binoculars,
  Biohazard,
  Bird,
  Bolt,
  Bomb,
  Bone,
  Book,
  BookOpen,
  BoomBox,
  BowArrow,
  BrickWall,
  BrickWallFire,
  Brush,
  Bug,
  Building,
  Cake,
  CakeSlice,
  Candy,
  CandyCane,
  Caravan,
  Carrot,
  Castle,
  Cat,
  ChefHat,
  Cherry,
  Church,
  Citrus,
  Clapperboard,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  Cloudy,
  Clover,
  Club,
  Coffee,
  Coins,
  Compass,
  Cone,
  Cookie,
  CookingPot,
  Croissant,
  Cross,
  Crosshair,
  Crown,
  Cuboid,
  CupSoda,
  Cylinder,
  Dam,
  Dessert,
  Diamond,
  Dice1,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Disc,
  Disc3,
  DiscAlbum,
  Dna,
  Dock,
  Dog,
  Donut,
  DoorClosed,
  DoorOpen,
  DraftingCompass,
  Drama,
  Drill,
  Droplet,
  Droplets,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  Earth,
  Eclipse,
  Egg,
  EggFried,
  Eraser,
  Eye,
  Factory,
  Fan,
  Feather,
  Fence,
  FerrisWheel,
  Film,
  FireExtinguisher,
  Fish,
  FishSymbol,
  Flag,
  FlagTriangleLeft,
  FlagTriangleRight,
  Flame,
  FlameKindling,
  Flashlight,
  FlaskConical,
  FlaskRound,
  Flower,
  Footprints,
  ForkKnife,
  ForkKnifeCrossed,
  Frown,
  Gamepad,
  Gauge,
  Gavel,
  Gem,
  Ghost,
  Gift,
  GlassWater,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Guitar,
  Ham,
  Hamburger,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  HandHelping,
  HandMetal,
  HandPlatter,
  Handshake,
  HardHat,
  Haze,
  Headset,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  Heater,
  HelpingHand,
  Hexagon,
  Highlighter,
  History,
  Home,
  Hop,
  Hospital,
  Hotel,
  Hourglass,
  House,
  IceCream,
  IceCreamBowl,
  IceCreamCone,
  Infinity,
  Joystick,
  Key,
  KeyRound,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  LandPlot,
  Landmark,
  Laugh,
  Leaf,
  LeafyGreen,
  Lectern,
  Library,
  LibraryBig,
  LifeBuoy,
  Lightbulb,
  Link,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
  Lollipop,
  Luggage,
  Magnet,
  Map,
  MapPin,
  MapPinned,
  Martini,
  Medal,
  Megaphone,
  Meh,
  Microscope,
  Milk,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Music,
  Music3,
  Music4,
  Nut,
  Octagon,
  Orbit,
  Origami,
  Package,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  PaintbrushVertical,
  Palmtree,
  Panda,
  PartyPopper,
  PawPrint,
  Pen,
  Pencil,
  Pentagon,
  PersonStanding,
  Piano,
  Pickaxe,
  PiggyBank,
  Pill,
  PillBottle,
  Pin,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  PocketKnife,
  Popcorn,
  Popsicle,
  Puzzle,
  Rabbit,
  Radiation,
  Radio,
  RadioReceiver,
  Rainbow,
  Rat,
  Recycle,
  Refrigerator,
  Ribbon,
  RollerCoaster,
  Route,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  Scroll,
  ScrollText,
  Search,
  Shapes,
  Shell,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldHalf,
  ShieldQuestion,
  Ship,
  ShipWheel,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrimp,
  Shrub,
  Signpost,
  SignpostBig,
  Siren,
  Skull,
  Slice,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Spade,
  Sparkle,
  Sparkles,
  SprayCan,
  Sprout,
  Squirrel,
  Stamp,
  Star,
  StarHalf,
  Stars,
  Store,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  SunSnow,
  Sunrise,
  Sunset,
  Sword,
  Swords,
  Syringe,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  TentTree,
  TestTube,
  TestTubeDiagonal,
  TestTubes,
  Theater,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Tornado,
  Tractor,
  Train,
  TrainFront,
  TrainTrack,
  Trash,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  Triangle,
  TriangleAlert,
  Trophy,
  Turtle,
  Umbrella,
  Unlink,
  Unlock,
  UnlockKeyhole,
  Utensils,
  UtensilsCrossed,
  Vault,
  VenetianMask,
  Wand,
  Wand2,
  WandSparkles,
  Warehouse,
  Watch,
  Waves,
  WavesLadder,
  Waypoints,
  Weight,
  Wheat,
  Wind,
  Wine,
  Worm,
  Wrench,
  type LucideIcon,
} from 'lucide-react'
import type { LucidePinIcon } from './mapPins'

export const PIN_ICON_COMPONENT: Record<LucidePinIcon, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  amphora: Amphora,
  anchor: Anchor,
  angry: Angry,
  annoyed: Annoyed,
  anvil: Anvil,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  armchair: Armchair,
  atom: Atom,
  award: Award,
  axe: Axe,
  baby: Baby,
  backpack: Backpack,
  banana: Banana,
  bath: Bath,
  beaker: Beaker,
  bean: Bean,
  bed: Bed,
  'bed-double': BedDouble,
  'bed-single': BedSingle,
  beef: Beef,
  beer: Beer,
  binoculars: Binoculars,
  biohazard: Biohazard,
  bird: Bird,
  bolt: Bolt,
  bomb: Bomb,
  bone: Bone,
  book: Book,
  'book-open': BookOpen,
  'boom-box': BoomBox,
  'bow-arrow': BowArrow,
  'brick-wall': BrickWall,
  'brick-wall-fire': BrickWallFire,
  brush: Brush,
  bug: Bug,
  building: Building,
  cake: Cake,
  'cake-slice': CakeSlice,
  candy: Candy,
  'candy-cane': CandyCane,
  caravan: Caravan,
  carrot: Carrot,
  castle: Castle,
  cat: Cat,
  'chef-hat': ChefHat,
  cherry: Cherry,
  church: Church,
  citrus: Citrus,
  clapperboard: Clapperboard,
  clock: Clock,
  cloud: Cloud,
  'cloud-drizzle': CloudDrizzle,
  'cloud-fog': CloudFog,
  'cloud-hail': CloudHail,
  'cloud-lightning': CloudLightning,
  'cloud-moon': CloudMoon,
  'cloud-moon-rain': CloudMoonRain,
  'cloud-rain': CloudRain,
  'cloud-rain-wind': CloudRainWind,
  'cloud-snow': CloudSnow,
  'cloud-sun': CloudSun,
  'cloud-sun-rain': CloudSunRain,
  cloudy: Cloudy,
  clover: Clover,
  club: Club,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  cone: Cone,
  cookie: Cookie,
  'cooking-pot': CookingPot,
  croissant: Croissant,
  cross: Cross,
  crosshair: Crosshair,
  crown: Crown,
  cuboid: Cuboid,
  'cup-soda': CupSoda,
  cylinder: Cylinder,
  dam: Dam,
  dessert: Dessert,
  diamond: Diamond,
  'dice-1': Dice1,
  'dice-3': Dice3,
  'dice-4': Dice4,
  'dice-5': Dice5,
  'dice-6': Dice6,
  disc: Disc,
  'disc-3': Disc3,
  'disc-album': DiscAlbum,
  dna: Dna,
  dock: Dock,
  dog: Dog,
  donut: Donut,
  'door-closed': DoorClosed,
  'door-open': DoorOpen,
  'drafting-compass': DraftingCompass,
  drama: Drama,
  drill: Drill,
  droplet: Droplet,
  droplets: Droplets,
  drum: Drum,
  drumstick: Drumstick,
  dumbbell: Dumbbell,
  ear: Ear,
  earth: Earth,
  eclipse: Eclipse,
  egg: Egg,
  'egg-fried': EggFried,
  eraser: Eraser,
  eye: Eye,
  factory: Factory,
  fan: Fan,
  feather: Feather,
  fence: Fence,
  'ferris-wheel': FerrisWheel,
  film: Film,
  'fire-extinguisher': FireExtinguisher,
  fish: Fish,
  'fish-symbol': FishSymbol,
  flag: Flag,
  'flag-triangle-left': FlagTriangleLeft,
  'flag-triangle-right': FlagTriangleRight,
  flame: Flame,
  'flame-kindling': FlameKindling,
  flashlight: Flashlight,
  'flask-conical': FlaskConical,
  'flask-round': FlaskRound,
  flower: Flower,
  footprints: Footprints,
  'fork-knife': ForkKnife,
  'fork-knife-crossed': ForkKnifeCrossed,
  frown: Frown,
  gamepad: Gamepad,
  gauge: Gauge,
  gavel: Gavel,
  gem: Gem,
  ghost: Ghost,
  gift: Gift,
  'glass-water': GlassWater,
  glasses: Glasses,
  globe: Globe,
  'graduation-cap': GraduationCap,
  grape: Grape,
  guitar: Guitar,
  ham: Ham,
  hamburger: Hamburger,
  hammer: Hammer,
  hand: Hand,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  'hand-helping': HandHelping,
  'hand-metal': HandMetal,
  'hand-platter': HandPlatter,
  handshake: Handshake,
  'hard-hat': HardHat,
  haze: Haze,
  headset: Headset,
  heart: Heart,
  'heart-crack': HeartCrack,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  heater: Heater,
  'helping-hand': HelpingHand,
  hexagon: Hexagon,
  highlighter: Highlighter,
  history: History,
  home: Home,
  hop: Hop,
  hospital: Hospital,
  hotel: Hotel,
  hourglass: Hourglass,
  house: House,
  'ice-cream': IceCream,
  'ice-cream-bowl': IceCreamBowl,
  'ice-cream-cone': IceCreamCone,
  infinity: Infinity,
  joystick: Joystick,
  key: Key,
  'key-round': KeyRound,
  lamp: Lamp,
  'lamp-ceiling': LampCeiling,
  'lamp-desk': LampDesk,
  'lamp-floor': LampFloor,
  'lamp-wall-down': LampWallDown,
  'lamp-wall-up': LampWallUp,
  'land-plot': LandPlot,
  landmark: Landmark,
  laugh: Laugh,
  leaf: Leaf,
  'leafy-green': LeafyGreen,
  lectern: Lectern,
  library: Library,
  'library-big': LibraryBig,
  'life-buoy': LifeBuoy,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  'lock-keyhole-open': LockKeyholeOpen,
  'lock-open': LockOpen,
  lollipop: Lollipop,
  luggage: Luggage,
  'magic-wand': Wand,
  magnet: Magnet,
  map: Map,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  martini: Martini,
  medal: Medal,
  megaphone: Megaphone,
  meh: Meh,
  microscope: Microscope,
  milk: Milk,
  moon: Moon,
  'moon-star': MoonStar,
  mountain: Mountain,
  'mountain-snow': MountainSnow,
  music: Music,
  'music-3': Music3,
  'music-4': Music4,
  nut: Nut,
  octagon: Octagon,
  orbit: Orbit,
  origami: Origami,
  package: Package,
  'paint-bucket': PaintBucket,
  'paint-roller': PaintRoller,
  paintbrush: Paintbrush,
  'paintbrush-vertical': PaintbrushVertical,
  palmtree: Palmtree,
  panda: Panda,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  pen: Pen,
  pencil: Pencil,
  pentagon: Pentagon,
  'person-standing': PersonStanding,
  piano: Piano,
  pickaxe: Pickaxe,
  'piggy-bank': PiggyBank,
  pill: Pill,
  'pill-bottle': PillBottle,
  pin: Pin,
  pizza: Pizza,
  plane: Plane,
  'plane-landing': PlaneLanding,
  'plane-takeoff': PlaneTakeoff,
  'pocket-knife': PocketKnife,
  popcorn: Popcorn,
  popsicle: Popsicle,
  puzzle: Puzzle,
  rabbit: Rabbit,
  radiation: Radiation,
  radio: Radio,
  'radio-receiver': RadioReceiver,
  rainbow: Rainbow,
  rat: Rat,
  recycle: Recycle,
  refrigerator: Refrigerator,
  ribbon: Ribbon,
  'roller-coaster': RollerCoaster,
  route: Route,
  ruler: Ruler,
  sailboat: Sailboat,
  salad: Salad,
  sandwich: Sandwich,
  scale: Scale,
  school: School,
  scissors: Scissors,
  scroll: Scroll,
  'scroll-text': ScrollText,
  search: Search,
  shapes: Shapes,
  shell: Shell,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-ban': ShieldBan,
  'shield-check': ShieldCheck,
  'shield-half': ShieldHalf,
  'shield-question': ShieldQuestion,
  ship: Ship,
  'ship-wheel': ShipWheel,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  shovel: Shovel,
  'shower-head': ShowerHead,
  shrimp: Shrimp,
  shrub: Shrub,
  signpost: Signpost,
  'signpost-big': SignpostBig,
  siren: Siren,
  skull: Skull,
  slice: Slice,
  smile: Smile,
  'smile-plus': SmilePlus,
  snail: Snail,
  snowflake: Snowflake,
  sofa: Sofa,
  soup: Soup,
  spade: Spade,
  sparkle: Sparkle,
  sparkles: Sparkles,
  'spray-can': SprayCan,
  sprout: Sprout,
  squirrel: Squirrel,
  stamp: Stamp,
  star: Star,
  'star-half': StarHalf,
  stars: Stars,
  store: Store,
  sun: Sun,
  'sun-dim': SunDim,
  'sun-medium': SunMedium,
  'sun-moon': SunMoon,
  'sun-snow': SunSnow,
  sunrise: Sunrise,
  sunset: Sunset,
  sword: Sword,
  swords: Swords,
  syringe: Syringe,
  tag: Tag,
  tags: Tags,
  target: Target,
  telescope: Telescope,
  tent: Tent,
  'tent-tree': TentTree,
  'test-tube': TestTube,
  'test-tube-diagonal': TestTubeDiagonal,
  'test-tubes': TestTubes,
  theater: Theater,
  thermometer: Thermometer,
  'thermometer-snowflake': ThermometerSnowflake,
  'thermometer-sun': ThermometerSun,
  tornado: Tornado,
  tractor: Tractor,
  train: Train,
  'train-front': TrainFront,
  'train-track': TrainTrack,
  trash: Trash,
  'tree-deciduous': TreeDeciduous,
  'tree-palm': TreePalm,
  'tree-pine': TreePine,
  trees: Trees,
  triangle: Triangle,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  turtle: Turtle,
  umbrella: Umbrella,
  unlink: Unlink,
  unlock: Unlock,
  'unlock-keyhole': UnlockKeyhole,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  vault: Vault,
  'venetian-mask': VenetianMask,
  wand: Wand2,
  'wand-sparkles': WandSparkles,
  warehouse: Warehouse,
  watch: Watch,
  waves: Waves,
  'waves-ladder': WavesLadder,
  waypoints: Waypoints,
  weight: Weight,
  wheat: Wheat,
  wind: Wind,
  wine: Wine,
  worm: Worm,
  wrench: Wrench,
}
