/**
 * The lucide component behind each ScriptIconKey - see scriptIcons.ts for
 * why the keys themselves live in a separate, import-free file (the same
 * split pinIcons.ts uses for map pins, and for the same reason).
 */
import {
  Activity,
  Anvil,
  Backpack,
  BookOpen,
  Bug,
  Cable,
  Coins,
  Compass,
  Dice5,
  DoorOpen,
  Eye,
  EyeOff,
  FileCode2,
  Fish,
  Flame,
  FlaskConical,
  Footprints,
  Gem,
  Hammer,
  HeartPulse,
  KeyRound,
  Landmark,
  Lock,
  LogOut,
  type LucideIcon,
  Map as MapIcon,
  Music,
  PawPrint,
  Pickaxe,
  Puzzle,
  Radar,
  RefreshCw,
  Repeat,
  Scissors,
  ScrollText,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Skull,
  Sparkles,
  Stethoscope,
  Sword,
  Swords,
  Terminal,
  Trees,
  Unlock,
  Wand2,
} from 'lucide-react'
import type { ScriptIconKey } from './scriptIcons'

/**
 * Every key `scriptIcons.ts` can emit, plus a handful (`flame`, `eye`,
 * `scroll`) no pattern currently produces on its own - kept in the palette
 * anyway, because `scriptIconOverrides.ts`'s picker offers this whole set
 * for a player to choose *by hand*, and a script whose best description is
 * "fire" or "watches" deserves that icon even if the automatic guesser
 * never reaches for it unprompted.
 */
export const SCRIPT_ICON_COMPONENT: Record<ScriptIconKey, LucideIcon> = {
  gem: Gem,
  sword: Sword,
  swords: Swords,
  shield: Shield,
  'shield-check': ShieldCheck,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  'eye-off': EyeOff,
  'log-out': LogOut,
  repeat: Repeat,
  skull: Skull,
  landmark: Landmark,
  coins: Coins,
  hammer: Hammer,
  anvil: Anvil,
  flame: Flame,
  'flask-conical': FlaskConical,
  pickaxe: Pickaxe,
  trees: Trees,
  scissors: Scissors,
  sparkles: Sparkles,
  wand: Wand2,
  scroll: ScrollText,
  map: MapIcon,
  compass: Compass,
  'door-open': DoorOpen,
  eye: Eye,
  radar: Radar,
  activity: Activity,
  'book-open': BookOpen,
  settings: Settings,
  'refresh-cw': RefreshCw,
  cable: Cable,
  lock: Lock,
  unlock: Unlock,
  'key-round': KeyRound,
  footprints: Footprints,
  'paw-print': PawPrint,
  bug: Bug,
  fish: Fish,
  music: Music,
  'dice-5': Dice5,
  puzzle: Puzzle,
  backpack: Backpack,
  'shopping-bag': ShoppingBag,
  'file-code': FileCode2,
  terminal: Terminal,
}
