//! The one definition of what a sign-in failure is called, on the Rust side.
//!
//! # Why this module exists
//!
//! `src/lib/lichLogin.ts` has always documented a contract: every failure from
//! `lich_login_characters` and `lich_login_launch` carries a **stable machine
//! code**, and the webview picks the player's sentence from that code rather
//! than from English prose, because prose gets reworded and the breakage is
//! silent — every error quietly becomes the generic one.
//!
//! Nothing on this side implemented it (issue #457). Both commands did
//! `.map_err(|e| e.to_string())` and [`crate::eaccess::EAccessError`]'s
//! `Display` writes prose with no code, so `classifyLoginError`'s token regexp
//! never matched, every real failure classified as `unknown`, and all seven
//! player sentences were unreachable in the shipped app. A locked account read
//! as *"Signing in failed. the account cannot sign in right now (LOCKED)"*.
//!
//! # The shape on the wire
//!
//! A structured object rather than a `"token: prose"` string:
//!
//! ```json
//! { "code": "account_locked_or_expired", "message": "the account cannot sign in right now (LOCKED)" }
//! ```
//!
//! Structured because a prefix convention is a parser waiting to be got wrong —
//! a message that happens to begin `something:` would be read as a code, and a
//! code containing a colon would be read as half of one. A Tauri command's
//! `Err` is serialised by serde like any other value, so the webview receives
//! this as an object and reads one field.
//!
//! # One code set, asserted on both sides
//!
//! [`LoginCode::ALL`] is the whole vocabulary. Its `as_str` values are the
//! snake_case names of [`crate::eaccess::EAccessError`]'s variants plus the
//! three failures that happen outside the protocol (the launcher, and the two
//! stored-password states N8 left unreachable — issue #459).
//!
//! The set is not copied into TypeScript by hand and hoped over:
//! `src/lib/loginErrorFixtures.ts` is **generated by a Rust test from these
//! types** (`the_fixture_is_the_real_serialisation` below), checked in, and
//! asserted fresh on every `cargo test`. `tools/sign-in-test.mjs` classifies
//! the strings in that fixture — the real `Display` output, not a token the
//! test built itself, which is exactly how #457 survived a green suite — and
//! `src/lib/lichLoginFake.ts` throws the same generated objects, so the
//! browser stand-in cannot produce a shape the backend never sends.

use serde::Serialize;

/// Every way signing in can fail, as a closed set of machine-readable codes.
///
/// The seven protocol codes are the snake_case forms of
/// [`crate::eaccess::EAccessError`]'s variant names, so the two vocabularies
/// cannot drift: `eaccess.rs`'s `code()` is a `match` over the enum and the
/// compiler refuses an unhandled variant.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LoginCode {
    /// `EAccessError::BadCredentials`.
    BadCredentials,
    /// `EAccessError::AccountLockedOrExpired`.
    AccountLockedOrExpired,
    /// `EAccessError::AccountRefused`. The login service said no with a token
    /// this version cannot read. Distinct from [`Self::BadCredentials`]
    /// because it is the code that must **not** cost the player the saved
    /// password (issue #488).
    AccountRefused,
    /// `EAccessError::NoSuchCharacter`.
    NoSuchCharacter,
    /// `EAccessError::ProtocolMismatch`.
    ProtocolMismatch,
    /// `EAccessError::PasswordLength`.
    PasswordLength,
    /// `EAccessError::ObscuredByteOutOfRange`.
    ObscuredByteOutOfRange,
    /// `EAccessError::Network`.
    Network,
    /// The account login worked and Lich did not: it could not be started, it
    /// exited before opening its detachable port, or it never opened it.
    /// One code because there is one thing the player does about all three,
    /// and the detail says which happened.
    LichDidNotStart,
    /// The account login worked and this app did **not** start Lich, because
    /// one is already running.
    ///
    /// Distinct from [`Self::LichDidNotStart`] because the two want opposite
    /// things from the player (issue #488 §3). "Did not start" is a fault to
    /// diagnose; this is a Lich that is up and can be attached to, which is
    /// the ordinary state after the app was closed while the character stayed
    /// logged in. Sending it to the diagnostic was the defect.
    LichAlreadyRunning,
    /// No password was sent and none is stored for this account.
    PasswordNeeded,
    /// A password *was* loaded from Windows Credential Manager and the account
    /// server refused it. Distinct from [`Self::BadCredentials`] because the
    /// player did not type anything to check, and because the stored entry has
    /// been forgotten by the time this is returned — so it must not read as
    /// "try that again".
    StoredPasswordRejected,
    /// Something inside this app, not the protocol and not the launcher: a
    /// worker thread that did not finish, and nothing else today.
    ///
    /// **The one code that deliberately classifies to `unknown`.** There is no
    /// advice to give a player about it, so the honest thing is the generic
    /// sentence with the raw detail after it, which is what
    /// `classifyLoginError` does for a code it does not recognise. It is in
    /// this set anyway so that "every code the webview can receive is written
    /// down on both sides" stays true — a code that only existed in Rust is
    /// how the next #457 would start.
    Internal,
}

impl LoginCode {
    /// Every code, in the order the fixture records them.
    ///
    /// The denominator for the fixture test: a code added to the enum and not
    /// to this array leaves the fixture short, and the test that counts it
    /// goes red naming the shortfall.
    pub const ALL: [LoginCode; 13] = [
        LoginCode::BadCredentials,
        LoginCode::AccountLockedOrExpired,
        LoginCode::AccountRefused,
        LoginCode::NoSuchCharacter,
        LoginCode::ProtocolMismatch,
        LoginCode::PasswordLength,
        LoginCode::ObscuredByteOutOfRange,
        LoginCode::Network,
        LoginCode::LichDidNotStart,
        LoginCode::LichAlreadyRunning,
        LoginCode::PasswordNeeded,
        LoginCode::StoredPasswordRejected,
        LoginCode::Internal,
    ];

    /// The string that crosses the boundary. snake_case, stable, and the only
    /// thing the webview matches on.
    pub fn as_str(self) -> &'static str {
        match self {
            LoginCode::BadCredentials => "bad_credentials",
            LoginCode::AccountLockedOrExpired => "account_locked_or_expired",
            LoginCode::AccountRefused => "account_refused",
            LoginCode::NoSuchCharacter => "no_such_character",
            LoginCode::ProtocolMismatch => "protocol_mismatch",
            LoginCode::PasswordLength => "password_length",
            LoginCode::ObscuredByteOutOfRange => "obscured_byte_out_of_range",
            LoginCode::Network => "network",
            LoginCode::LichDidNotStart => "lich_did_not_start",
            LoginCode::LichAlreadyRunning => "lich_already_running",
            LoginCode::PasswordNeeded => "password_needed",
            LoginCode::StoredPasswordRejected => "stored_password_rejected",
            LoginCode::Internal => "internal",
        }
    }
}

/// What a failing sign-in command returns.
///
/// **No field of this may ever carry a password.** `message` is a `Display` of
/// an error type whose own tests assert the same thing
/// (`password_never_reaches_an_error_string` in `eaccess.rs`), and
/// `credentials.rs`'s source walker refuses any formatting macro that names a
/// password binding.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct LoginFailure {
    /// One of [`LoginCode::ALL`], as a string.
    pub code: &'static str,
    /// Whatever detail is safe to print. Shown under the player's sentence,
    /// not instead of it.
    pub message: String,
}

impl LoginFailure {
    pub fn new(code: LoginCode, message: impl Into<String>) -> Self {
        Self {
            code: code.as_str(),
            message: message.into(),
        }
    }

    /// The launcher half: Lich could not be started, exited, or never listened.
    pub fn lich_did_not_start(message: impl Into<String>) -> Self {
        Self::new(LoginCode::LichDidNotStart, message)
    }

    /// The account login worked and a Lich was already up, so this app started
    /// none. See [`LoginCode::LichAlreadyRunning`].
    pub fn lich_already_running(message: impl Into<String>) -> Self {
        Self::new(LoginCode::LichAlreadyRunning, message)
    }

    /// Nothing was typed and nothing is stored.
    pub fn password_needed(account: &str) -> Self {
        Self::new(
            LoginCode::PasswordNeeded,
            format!("no password was sent and none is saved for {account}"),
        )
    }

    /// The stored password was refused, and has been forgotten.
    pub fn stored_password_rejected(detail: &str) -> Self {
        Self::new(
            LoginCode::StoredPasswordRejected,
            format!("the saved password was refused and has been removed ({detail})"),
        )
    }

    /// Something inside this app, with no advice attached. See
    /// [`LoginCode::Internal`].
    pub fn internal(message: impl Into<String>) -> Self {
        Self::new(LoginCode::Internal, message)
    }
}

impl std::fmt::Display for LoginFailure {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // The legacy string form, for the one caller that still takes a
        // `String` error (`launch_lich`, which opens Lich's own window and is
        // not a sign-in). Deliberately not the shape the webview parses: the
        // sign-in path returns the struct, and this exists so no information
        // is lost when a `LoginFailure` has to be flattened.
        write!(f, "{}: {}", self.code, self.message)
    }
}

impl std::error::Error for LoginFailure {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_code_has_a_distinct_snake_case_string() {
        let mut seen = std::collections::BTreeSet::new();
        for code in LoginCode::ALL {
            let s = code.as_str();
            assert!(
                s.chars().all(|c| c.is_ascii_lowercase() || c == '_'),
                "{s} is not snake_case"
            );
            assert!(seen.insert(s), "{s} appears twice in LoginCode::ALL");
        }
        // The denominator: a variant added to the enum but not to `ALL` makes
        // this number wrong, and the fixture built from `ALL` would then be
        // silently short a code.
        assert_eq!(seen.len(), LoginCode::ALL.len());
    }

    /// One real failure per code, in `LoginCode::ALL`'s order.
    ///
    /// The messages come from the error types' own `Display`, never from a
    /// string written here: the whole point of the fixture is that the webview
    /// is classifying **what Rust actually sends**. `tools/sign-in-test.mjs`
    /// used to build its own token and then check that the classifier could
    /// read it, which is why #457 survived fifty-five green checks.
    fn every_failure() -> Vec<LoginFailure> {
        use crate::eaccess::EAccessError;
        // The three refusals come from the classifier, never from a variant
        // written here (issue #488). A hand-built pair is how this file came
        // to ship `AccountLockedOrExpired { code: "NEW" }` — a state the live
        // pipeline could not produce for that token, because `NEW` classified
        // as `BadCredentials` and cost the player their saved password. That
        // is #457's defect one level in, in the module written to prevent it.
        // Passing the token through `from_refusal_code` means a fixture can
        // only ever record what a server sending that token really gets.
        let protocol = [
            EAccessError::from_refusal_code("PASSWORD"),
            EAccessError::from_refusal_code("LOCKED"),
            EAccessError::from_refusal_code("NEW"),
            EAccessError::NoSuchCharacter {
                requested: "Nobody".into(),
                available: 3,
            },
            EAccessError::ProtocolMismatch {
                step: "A",
                saw: "something this version does not know".into(),
            },
            EAccessError::PasswordLength {
                password_len: 40,
                hashkey_len: 32,
            },
            EAccessError::ObscuredByteOutOfRange { index: 7 },
            EAccessError::Network {
                endpoint: "eaccess.play.net:7910".into(),
                detail: "could not connect: connection refused".into(),
            },
        ];
        let mut out: Vec<LoginFailure> = protocol.into_iter().map(LoginFailure::from).collect();
        // No port number in this sample, deliberately: `tools/detachable-port-test.mjs`
        // holds the line that 11024 is declared once, in `lich::DETACHABLE_PORT`,
        // and a fixture message is not a place to retype it.
        out.push(LoginFailure::lich_did_not_start(
            "Lich started and then exited with code 1 without opening its detachable port.",
        ));
        out.push(LoginFailure::lich_already_running(
            "a Lich is already running, so this app did not start a second one",
        ));
        out.push(LoginFailure::password_needed("demo"));
        out.push(LoginFailure::stored_password_rejected(
            "the account name or password was not accepted (PASSWORD)",
        ));
        out.push(LoginFailure::internal(
            "the sign-in task did not finish: task panicked",
        ));
        out
    }

    /// The generated module, as text.
    ///
    /// A TypeScript module rather than a JSON file so the webview, the browser
    /// stand-in and the Node suite all read the *same* artefact with no build
    /// configuration: `tsconfig.app.json` includes `src` and does not enable
    /// `resolveJsonModule`, so a JSON fixture would have needed a second copy
    /// somewhere to be usable, and a second copy is the thing this file exists
    /// to prevent. The bodies are `serde_json` strings, so escaping is the
    /// serialiser's problem and not a hand-written one.
    fn render_fixture(failures: &[LoginFailure]) -> String {
        let mut out = String::new();
        out.push_str(
            r#"/**
 * Every failure the Rust side can send, as it really serialises it.
 *
 * **Generated. Do not edit.** `src-tauri/src/login_error.rs`'s
 * `the_fixture_is_the_real_serialisation` writes this from the Rust types and
 * fails on every `cargo test` if the checked-in copy has drifted. Regenerate
 * with `DRC_WRITE_LOGIN_FIXTURE=1 cargo test login_error` in `src-tauri`.
 *
 * It exists because issue #457 was a contract nobody checked: the webview's
 * classifier was fed strings the test itself had built, so it passed while the
 * backend sent something else entirely. Anything that wants to know what a
 * failure looks like reads this, and this is written by the code that sends
 * them.
 */
export interface LoginErrorFixture {
  code: string
  message: string
}

export const LOGIN_ERROR_FIXTURES: LoginErrorFixture[] = [
"#,
        );
        for failure in failures {
            let code = serde_json::to_string(failure.code).expect("a code serialises");
            let message = serde_json::to_string(&failure.message).expect("a message serialises");
            out.push_str(&format!("  {{ code: {code}, message: {message} }},\n"));
        }
        out.push_str("]\n");
        out
    }

    /// `src/lib/loginErrorFixtures.ts` is the real serialisation, and stays
    /// that way.
    ///
    /// Generated here rather than typed anywhere, checked in so the webview and
    /// the Node suite can read it with no Rust toolchain, and compared on every
    /// `cargo test` so it cannot go stale. Regenerate with
    /// `DRC_WRITE_LOGIN_FIXTURE=1 cargo test login_error` in `src-tauri`.
    ///
    /// The denominator is asserted before the comparison: a fixture short a
    /// code, or a `every_failure` that stopped covering one, must be a failure
    /// naming the code rather than a shorter file that still round-trips.
    #[test]
    fn the_fixture_is_the_real_serialisation() {
        let failures = every_failure();
        let covered: Vec<&'static str> = failures.iter().map(|f| f.code).collect();
        for code in LoginCode::ALL {
            assert!(
                covered.contains(&code.as_str()),
                "{} has no sample in every_failure(); the fixture would be silently short a code",
                code.as_str()
            );
        }
        assert_eq!(
            failures.len(),
            LoginCode::ALL.len(),
            "the fixture has {} entries for {} codes",
            failures.len(),
            LoginCode::ALL.len()
        );
        // Order too, not only coverage: the fixture is read positionally by
        // nothing, but a sample that drifts out of `ALL`'s order is a sample
        // somebody has re-typed rather than re-derived.
        assert_eq!(
            covered,
            LoginCode::ALL.map(|c| c.as_str()).to_vec(),
            "every_failure() is out of LoginCode::ALL order"
        );
        for failure in &failures {
            assert!(
                !failure.message.trim().is_empty(),
                "{} has an empty message; the webview would show a bare sentence",
                failure.code
            );
        }

        let rendered = render_fixture(&failures);

        let path = std::path::Path::new("..").join("src/lib/loginErrorFixtures.ts");

        // Read **before** any write (issue #488 §5). The old order was write,
        // then read, then compare - so a run with `DRC_WRITE_LOGIN_FIXTURE=1`
        // set both repaired the drift and passed, in the same run, and a drift
        // nobody was ever told about is exactly the state this test exists to
        // make impossible. That is the pattern #464 gated everywhere else,
        // arriving in the test that guards the contract.
        //
        // A missing file is a real "cannot tell" and not a drift, so it keeps
        // its own message: an empty string would compare unequal and report
        // drift for a file that is not there.
        let before = std::fs::read_to_string(&path).ok();

        let asked_to_write = std::env::var("DRC_WRITE_LOGIN_FIXTURE").is_ok_and(|v| v == "1");
        let drifted = before.as_deref().map(|c| c.replace("\r\n", "\n")) != Some(rendered.clone());

        if asked_to_write && drifted {
            std::fs::create_dir_all(path.parent().expect("a parent")).expect("the fixture dir");
            std::fs::write(&path, &rendered).expect("the fixture writes");
            // Written, and still a failure. A regeneration is a repair, and a
            // repair is a thing a person has to see and commit; a green run
            // here would mean the drift left no trace anywhere. Running the
            // suite again without the variable is what passes, and that pass
            // is the proof the repair worked.
            panic!(
                "{} had drifted and DRC_WRITE_LOGIN_FIXTURE=1 has just rewritten it. \
                 Commit the regenerated file and run the tests again without that \
                 variable set; this run does not pass on a fixture it repaired itself.",
                path.display()
            );
        }
        if asked_to_write {
            // Asked to write, nothing to write. Said out loud so a regeneration
            // that turns out to be a no-op is visible, rather than looking like
            // a successful repair.
            eprintln!(
                "login_error: DRC_WRITE_LOGIN_FIXTURE=1 but {} was already current; nothing written",
                path.display()
            );
        }

        let current = before.unwrap_or_else(|| {
            panic!(
                "{} is missing; regenerate with DRC_WRITE_LOGIN_FIXTURE=1 cargo test",
                path.display()
            )
        });
        assert_eq!(
            current.replace("\r\n", "\n"),
            rendered,
            "{} has drifted from the Rust types; regenerate with \
             DRC_WRITE_LOGIN_FIXTURE=1 cargo test",
            path.display()
        );
    }

    /// #488: the fixture's refusal samples are what the classifier produces
    /// for those tokens, and the three of them are three *different* codes.
    ///
    /// The negative control is `NEW`. Before #488 it was written into this
    /// file by hand as `AccountLockedOrExpired`, which no server sending `NEW`
    /// could ever have produced; this asserts the fixture and the pipeline
    /// agree, and it goes red if anyone hand-builds a variant here again.
    #[test]
    fn the_refusal_samples_are_the_classifier_s_own_answers() {
        use crate::eaccess::EAccessError;
        let by_token = |t: &str| EAccessError::from_refusal_code(t).code().as_str();
        assert_eq!(by_token("PASSWORD"), "bad_credentials");
        assert_eq!(by_token("LOCKED"), "account_locked_or_expired");
        assert_eq!(by_token("NEW"), "account_refused");
        // And the samples in the fixture are exactly those, in that order.
        let refusals: Vec<&str> = every_failure().iter().take(3).map(|f| f.code).collect();
        assert_eq!(
            refusals,
            vec![by_token("PASSWORD"), by_token("LOCKED"), by_token("NEW")]
        );
    }

    #[test]
    fn a_failure_serialises_as_the_webview_reads_it() {
        let failure = LoginFailure::new(LoginCode::AccountLockedOrExpired, "the account is locked");
        let json = serde_json::to_string(&failure).expect("a failure serialises");
        assert_eq!(
            json,
            r#"{"code":"account_locked_or_expired","message":"the account is locked"}"#
        );
    }
}
