import { readFileSync } from 'node:fs'

let failures = 0
function check(label, value) {
  if (value) console.log(`OK   ${label}`)
  else { console.error(`FAIL ${label}`); failures += 1 }
}

const battle = readFileSync(new URL('../src/components/room/BattleColumn.tsx', import.meta.url), 'utf8')
const actions = readFileSync(new URL('../src/components/room/BattleActionBar.tsx', import.meta.url), 'utf8')
const chat = readFileSync(new URL('../src/components/room/GameChatColumn.tsx', import.meta.url), 'utf8')
const radar = readFileSync(new URL('../src/components/shared/CombatRadar.tsx', import.meta.url), 'utf8')
const scene = readFileSync(new URL('../src/components/room/RoomScene.tsx', import.meta.url), 'utf8')
const backdrop = readFileSync(new URL('../src/components/room/RoomBackdrop.tsx', import.meta.url), 'utf8')
const floor = readFileSync(new URL('../src/components/room/FloorItems.tsx', import.meta.url), 'utf8')
const inventory = readFileSync(new URL('../src/components/shared/InventoryPanel.tsx', import.meta.url), 'utf8')
const taskflows = readFileSync(new URL('../src/components/dashboard/TaskFlowPanel.tsx', import.meta.url), 'utf8')
const paperdoll = readFileSync(new URL('../src/components/shared/Paperdoll.tsx', import.meta.url), 'utf8')
const actionVisuals = readFileSync(new URL('../src/lib/battleActionVisuals.ts', import.meta.url), 'utf8')
const hotbar = readFileSync(new URL('../src/components/layout/QuickSwitchBar.tsx', import.meta.url), 'utf8')
const quickSwitch = readFileSync(new URL('../src/lib/quickSwitch.ts', import.meta.url), 'utf8')
const map = readFileSync(new URL('../src/components/shared/MapPanel.tsx', import.meta.url), 'utf8')
const grokScenes = readFileSync(new URL('../src/data/grokRoomScenes.ts', import.meta.url), 'utf8')

check('the battle scene uses a landscape tactical field', /shape="landscape"/.test(battle) && /aspect-\[4\/3\]/.test(scene))
check('room details and inventory receive the remaining useful height', /min-h-\[13rem\][^"']*flex-1/.test(battle))
check('the full room description is permanently below the battle', /aria-label="Room description"/.test(battle) && /<ClassicRoomText/.test(battle))
check('inventory is permanently visible beside the room description', /aria-label="Inventory"/.test(battle) && /<InventoryPanel/.test(battle))
check('combat controls use the complete grouped macro catalog', /MACROS\.filter/.test(actions) && /'combat'/.test(actions) && /'goods'/.test(actions) && /'magic'/.test(actions))
check('every combat variation is a directly wired compact icon button', /macro\.variations\.map/.test(actions) && /onClick=\{\(\) => run\(variation\.commands\)\}/.test(actions) && /h-9 w-9/.test(actions))
check('game and multiple taskflows permanently share the large split workspace', /grid-cols-\[minmax\(0,1\.35fr\)_minmax\(18rem,0\.85fr\)\]/.test(chat) && /Game and automation workspace/.test(chat) && /title="Functions & scripts"/.test(chat) && /<StreamTabs/.test(chat) && /<TaskFlowPanel/.test(chat) && !/paneMode/.test(chat))
check('the functions title and global catalog controls share one toolbar', /title\?: string/.test(taskflows) && /h-10 shrink-0 items-center/.test(taskflows) && /Filter tasks and scripts/.test(taskflows) && !/A filter across everything/.test(taskflows))
check('the game title and channel filters share one toolbar', /heading=\{<>/.test(chat) && /heading\?: ReactNode/.test(readFileSync(new URL('../src/components/game/StreamTabs.tsx', import.meta.url), 'utf8')) && !/h-10 shrink-0 items-center.*Game/.test(chat))
check('inventory title, search, and load share one toolbar', /flex min-w-0 items-center gap-2 text-xs/.test(inventory) && /shrink-0 \$\{pressureColor\}/.test(inventory))
check('battle controls do not duplicate functions and scripts', !/Scripts and workflows/.test(actions) && !/scriptCatalog/.test(actions))
check('floor items overlay the bottom of the room art instead of consuming another row', /footer=\{roomItems/.test(battle) && /bottom-0 z-30/.test(scene) && /from-black\/72/.test(scene) && !/shrink-0 rounded border border-border bg-surface-raised px-2 py-1\.5/.test(battle))
check('actor hover cards expose live facts, profile facts, game actions, and Elanthipedia', /playerProfileFor/.test(radar) && /label="Race"/.test(radar) && /label="Guild"/.test(radar) && /Right now/.test(radar) && /Bestiary/.test(radar) && /sendGame\(`look/.test(radar) && /sendGame\(`assess/.test(radar) && /Special:Search/.test(radar) && /pointer-events-auto/.test(radar))
check('the functions pane launches every basic macro variation beside every discovered script', /MACROS\.flatMap/.test(taskflows) && /runMacro\(variation\.commands\)/.test(taskflows) && /command\.\$\{macro\.id\}/.test(taskflows) && /rubyScripts/.test(taskflows) && /listScripts\(\)/.test(taskflows))
check('the radar has persistent grab-scroll enemy and friendly columns', /label="Enemies"/.test(radar) && /label="Friends"/.test(radar) && /Scrollable friendly and enemy radar columns/.test(radar) && /side="left"/.test(radar) && /side="right"/.test(radar) && /useDragScroll/.test(radar))
check('radar rails are transparent textless overlays on the battle map', /bg-transparent touch-none/.test(radar) && !/Combat radar<\/span>/.test(radar) && !/tone="friendly"/.test(radar) && !/sticky top-0 z-10 py-1 text-center/.test(radar))
check('removing radar chrome keeps the activity icon used by player status', /import \{ Activity,/.test(radar) && /Activity[^\n]*LucideIcon/.test(radar))
check('room art is the fixed base layer underneath the tactical radar', /aria-label="Room art"/.test(scene) && /absolute inset-0 z-0/.test(scene) && /aria-label="Tactical radar over room art"/.test(scene) && /absolute inset-0 z-10/.test(scene))
check('every successfully decoded room image fades over the deterministic fallback', /onLoad=/.test(backdrop) && /style\.opacity = '1'/.test(backdrop) && /onError=/.test(backdrop) && /style\.opacity = '0'/.test(backdrop) && /opacity-0 transition-opacity/.test(backdrop) && !/MIN_ROOM_ART_WIDTH/.test(backdrop))
check('generic room art comes only from stable location-aware Grok landscape baskets', /grokRoomScene\(zone, room, title, text\)/.test(readFileSync(new URL('../src/lib/roomText.ts', import.meta.url), 'utf8')) && /HOLD_ROOMS = 3/.test(grokScenes) && /\/grok-art\/room-scenes\//.test(grokScenes) && !/\/rooms\//.test(grokScenes) && !/\/room-scenes\//.test(grokScenes.replaceAll('/grok-art/room-scenes/', '')))
check('room exits are always wired from live compass or mapped movement commands', /stream\.compass\?\.value \?\? here\?\.moves/.test(battle))
check('large floor piles collapse duplicates and become searchable', /count: number/.test(floor) && /groups\.length > 12/.test(floor) && /Find among/.test(floor))
check('floor items open explicit actions instead of taking immediately', /Actions for/.test(floor) && />Look</.test(floor) && />Get</.test(floor) && />Appraise</.test(floor) && />Analyze</.test(floor))
check('floor and carried items link to Elanthipedia searches', /Special:Search/.test(floor) && /Special:Search/.test(inventory) && /Full Elanthipedia page/.test(inventory))
check('carried duplicates collapse into stable counted rows', /function groupedItems/.test(inventory) && /count > 1/.test(inventory) && /key=\{name\}/.test(inventory))
check('late wiki replies cannot replace the currently selected item', /wikiRequest/.test(inventory) && /request === wikiRequest\.current/.test(inventory))
check('inventory search reveals matching bags and contents', /container\.items.*\.some/.test(inventory) && /revealedBySearch/.test(inventory) && /Nothing carried matches/.test(inventory))
check('containers expose their own Elanthipedia action', /Elanthipedia information for \$\{c\.name\}/.test(inventory) && /showWiki\(c\.name\)/.test(inventory))
check('the central player dashboard is a compact oval', /rounded-full bg-surface\/70/.test(radar) && /max-w-\[15rem\]/.test(radar))
check('the paperdoll uses the live bleed report instead of guessing from wound severity', /bleeding\?: Array/.test(paperdoll) && /isActiveBleed/.test(paperdoll) && !/inj\.wound >= 2 && <BloodStamp/.test(paperdoll))
check('the radar exposes every combat-critical and tactical status feed', /bags_full/.test(radar) && /roundtime/.test(radar) && /hidden/.test(radar) && /invisible/.test(radar) && /joined/.test(radar) && /character\?\.roundtime/.test(battle))
check('every battle action has a unique explicit icon contract', /const ACTION_ICONS/.test(actionVisuals) && /missingVisuals/.test(actionVisuals) && /duplicateIcons/.test(actionVisuals) && /throw new Error/.test(actionVisuals))
check('every battle action is directly wired to its exact commands', /data-action=\{actionKey\}/.test(actions) && /onClick=\{\(\) => run\(variation\.commands\)\}/.test(actions) && /Runs: \$\{variation\.commands\.join/.test(actions))
check('every battle action receives a unique stable color signature', /ACTION_INDEX/.test(actionVisuals) && /137\.508/.test(actionVisuals) && /style=\{actionAccent\(actionKey\)\}/.test(actions))
check('the complete functions launcher reuses semantic command icons and uniquely colors every tile', /actionKey: `\$\{macro\.id\}:\$\{variation\.id\}`/.test(taskflows) && /actionIcon\(entry\.actionKey\)/.test(taskflows) && /accentForIndex\(entryVisualIndex/.test(taskflows) && /data-entry-id=\{entry\.id\}/.test(taskflows))
check('unavailable command buttons are honestly disabled instead of accepting dead clicks', /disabled: !canSendMacro/.test(taskflows) && /disabled=\{entry\.disabled\}/.test(taskflows))
check('library commands can be added to and removed from the shared hotbar', /kind: 'command'/.test(quickSwitch) && /kind: 'command', actionKey: entry\.actionKey/.test(taskflows) && /Remove .* from the hotbar/.test(hotbar) && /togglePin\(slot\.pin\)/.test(hotbar))
check('hotbar commands keep their exact icon, color, tooltip, and macro execution path', /actionIcon\(pin\.actionKey\)/.test(hotbar) && /actionAccent\(pin\.actionKey\)/.test(hotbar) && /variation\.commands\.join/.test(hotbar) && /macro\.run\(variation\.commands\)/.test(hotbar))
check('map title, character, search and controls share one compact header line', /search=\{<PlaceSearch/.test(map) && /<header className="flex min-w-0 items-start gap-2"/.test(map) && !/gives is a place on the map/.test(map))
check('room title, hands and statuses share the scene header line', /header=\{<PanelBoundary label="Status"><BattleStatus/.test(battle) && /absolute inset-x-0 top-0 z-30 flex/.test(scene))

if (failures) process.exit(1)
console.log('\nall battlespace checks passed')
