// Generated by tools/build-room-scene-patterns.mjs. Edit data/art/scene-baskets.json instead.
type PatternRule = { zone: string; ranges: readonly (readonly [number, number])[]; arts: readonly string[] }
const HOLD_ROOMS = 3
const RULES: readonly PatternRule[] = [
  {"zone":"1","ranges":[[8,8],[11,11],[18,18],[29,31]],"arts":["/room-scenes/town-crossing-master.webp"]}, // 1::Clanthew Boulevard
  {"zone":"1","ranges":[[129,132]],"arts":["/room-scenes/town-crossing-master.webp"]}, // 1::Gildleaf Circle
  {"zone":"1","ranges":[[177,183]],"arts":["/room-scenes/town-crossing-master.webp"]}, // 1::Riverpine Circle
  {"zone":"1","ranges":[[264,273]],"arts":["/room-scenes/town-crossing-master.webp"]}, // 1::Midton Circle
  {"zone":"1","ranges":[[516,522]],"arts":["/room-scenes/master-garden.webp"]}, // 1::Gardens
  {"zone":"1","ranges":[[607,610],[612,614]],"arts":["/room-scenes/town-crossing-master.webp"]}, // 1::Smithy Lane
  {"zone":"1","ranges":[[806,810]],"arts":["/room-scenes/town-crossing-master.webp"]}, // 1::Holy Warrior's Promenade
  {"zone":"1","ranges":[[1052,1057]],"arts":["/room-scenes/town-crossing-master.webp"]}, // 1::Riverlace Lane
  {"zone":"1a","ranges":[[12,17]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 1a::Under the Segoltha
  {"zone":"1a","ranges":[[18,21]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 1a::Passage
  {"zone":"2","ranges":[[31,50]],"arts":["/room-scenes/master-forest-path.webp"]}, // 2::Deep Tangle
  {"zone":"2a","ranges":[[146,153]],"arts":["/room-scenes/master-garden.webp"]}, // 2a::Gardens
  {"zone":"2d","ranges":[[10,11],[13,13],[15,16],[25,27],[30,30],[40,44],[46,46],[48,49]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 2d::Tower Tunnels
  {"zone":"2d","ranges":[[17,23]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 2d::Truffenyi's Way
  {"zone":"2d","ranges":[[31,38]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 2d::Kuniyo's Egress
  {"zone":"2d","ranges":[[50,56]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 2d::Chadatru's Vigil
  {"zone":"4","ranges":[[46,47],[74,78]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 4::Farmlands
  {"zone":"4","ranges":[[48,51],[55,55],[65,68],[70,72]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 4::Grain Fields
  {"zone":"4","ranges":[[234,237]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 4::Doline
  {"zone":"6","ranges":[[26,35],[38,38],[40,40],[44,44],[48,49],[58,58],[65,65],[67,79],[85,92],[269,270],[272,272],[274,285],[290,292],[294,294],[296,301]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 6::Brambles
  {"zone":"6","ranges":[[205,208]],"arts":["/room-scenes/master-garden.webp"]}, // 6::Courtyard
  {"zone":"7","ranges":[[152,156]],"arts":["/room-scenes/master-garden.webp"]}, // 7::Low Rise
  {"zone":"7","ranges":[[299,305],[309,309],[311,311]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 7::Fields
  {"zone":"7","ranges":[[329,332],[341,342],[355,356],[371,372],[400,400]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 7::Open Grasslands
  {"zone":"7","ranges":[[414,431],[433,433]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 7::Tunnels
  {"zone":"7","ranges":[[463,465],[810,813]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 7::Rocky Pass
  {"zone":"7c","ranges":[[6,10]],"arts":["/room-scenes/master-garden.webp"]}, // 7c::Chancellor's Gardens
  {"zone":"10","ranges":[[48,59]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 10::Stony Labyrinth
  {"zone":"11","ranges":[[149,157]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 11::Deep
  {"zone":"12a","ranges":[[22,39],[52,57]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 12a::Labyrinth
  {"zone":"12a","ranges":[[40,44]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 12a::Sepulcher
  {"zone":"12a","ranges":[[46,51]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 12a::Sanctum Sanctorum
  {"zone":"13","ranges":[[91,114]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 13::Ossuary Caverns
  {"zone":"13","ranges":[[189,195]],"arts":["/room-scenes/master-garden.webp"]}, // 13::Courtyard
  {"zone":"14b","ranges":[[170,174]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 14b::Uneven Slope
  {"zone":"14c","ranges":[[1,1],[3,19]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 14c::Faldesu River
  {"zone":"30","ranges":[[125,130],[212,212],[319,319]],"arts":["/room-scenes/master-garden.webp"]}, // 30::Garden
  {"zone":"30","ranges":[[284,287],[289,295]],"arts":["/room-scenes/town-riverhaven-master.webp"]}, // 30::Blossom Circle
  {"zone":"30a","ranges":[[9,19]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 30a::Catacombs
  {"zone":"31","ranges":[[43,45],[140,141],[143,147],[149,149],[151,151],[153,164]],"arts":["/room-scenes/master-wild-swamp.webp"]}, // 31::Wandering The Muck
  {"zone":"31","ranges":[[54,58]],"arts":["/room-scenes/master-wild-swamp.webp"]}, // 31::A Shallow Pool
  {"zone":"31","ranges":[[61,61],[136,138]],"arts":["/room-scenes/master-wild-swamp.webp"]}, // 31::Beside The Fence
  {"zone":"31","ranges":[[131,134]],"arts":["/room-scenes/master-wild-swamp.webp"]}, // 31::Stagnant Pool
  {"zone":"31b","ranges":[[7,48]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 31b::Murky Caverns
  {"zone":"31b","ranges":[[49,66],[68,70],[75,76]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 31b::Charred Caverns
  {"zone":"31b","ranges":[[98,105]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 31b::Underground River
  {"zone":"35","ranges":[[19,21],[31,31]],"arts":["/room-scenes/master-garden.webp"]}, // 35::Garden District
  {"zone":"40","ranges":[[69,82],[84,84],[90,92],[95,99]],"arts":["/room-scenes/master-wild-swamp.webp"]}, // 40::Gwenalion Fens
  {"zone":"40","ranges":[[85,88],[94,94],[100,112]],"arts":["/room-scenes/master-wild-swamp.webp"]}, // 40::Dried Reed Hummock
  {"zone":"40","ranges":[[322,343]],"arts":["/room-scenes/master-wild-swamp.webp"]}, // 40::In the Water
  {"zone":"40a","ranges":[[39,45]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 40a::Grasslands
  {"zone":"40a","ranges":[[104,105],[146,155]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 40a::Clover Fields
  {"zone":"41","ranges":[[54,59]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 41::Ascent
  {"zone":"42","ranges":[[116,116],[137,168],[338,346]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 42::The Breech Tunnels
  {"zone":"42","ranges":[[299,302]],"arts":["/room-scenes/master-garden.webp"]}, // 42::Sister Nongwen's Garden
  {"zone":"47","ranges":[[7,10]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Stoneworkers
  {"zone":"47","ranges":[[12,15],[64,64]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Performers
  {"zone":"47","ranges":[[16,16],[23,24],[26,26]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Instrument Makers
  {"zone":"47","ranges":[[17,21]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Nobles
  {"zone":"47","ranges":[[25,25],[27,30]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Alchemists
  {"zone":"47","ranges":[[39,42]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Potters
  {"zone":"47","ranges":[[43,46]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Cloth Weavers
  {"zone":"47","ranges":[[47,47],[67,68],[71,71]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Priests
  {"zone":"47","ranges":[[48,48],[51,54]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Metalsmiths
  {"zone":"47","ranges":[[315,321]],"arts":["/room-scenes/town-muspar-i-city-street-0.webp","/room-scenes/town-muspar-i-city-street-1.webp","/room-scenes/town-muspar-i-city-street-2.webp"]}, // 47::Street of Proprietors
  {"zone":"47","ranges":[[379,390]],"arts":["/room-scenes/master-desert-trail.webp","/room-scenes/archetype-desert-1.webp","/room-scenes/archetype-desert-6.webp"]}, // 47::Walk of Bones
  {"zone":"47","ranges":[[429,429],[433,437]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 47::Heke'mhhg River
  {"zone":"47","ranges":[[441,455]],"arts":["/room-scenes/master-desert-trail.webp","/room-scenes/archetype-desert-1.webp","/room-scenes/archetype-desert-6.webp"]}, // 47::Migen'hhs Pat'shhry
  {"zone":"50","ranges":[[4,6],[33,33]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 50::North Bank
  {"zone":"50","ranges":[[7,7],[9,11],[16,21],[32,32]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 50::Midstream
  {"zone":"50","ranges":[[12,15]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 50::Near the Boulder
  {"zone":"60","ranges":[[88,93]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 60::The River Bank
  {"zone":"60","ranges":[[125,128]],"arts":["/room-scenes/master-forest-path.webp"]}, // 60::Willow Valley
  {"zone":"60","ranges":[[132,136]],"arts":["/room-scenes/master-forest-path.webp"]}, // 60::Tangled Bosk
  {"zone":"60","ranges":[[147,155]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 60::Sushu Rahat
  {"zone":"60","ranges":[[160,165]],"arts":["/room-scenes/master-garden.webp"]}, // 60::Shaded Pathway
  {"zone":"61","ranges":[[3,12],[24,24],[47,47],[49,65],[67,68]],"arts":["/room-scenes/town-leth-deriel-master.webp"]}, // 61::Elder Bark Circle
  {"zone":"61","ranges":[[15,15],[21,21],[29,31],[33,40],[80,82]],"arts":["/room-scenes/town-leth-deriel-master.webp"]}, // 61::Cambium Circle
  {"zone":"61","ranges":[[17,17],[19,19],[25,27],[44,44],[72,72],[79,79]],"arts":["/room-scenes/town-leth-deriel-master.webp"]}, // 61::Oakenheart Circle
  {"zone":"61","ranges":[[262,265]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 61::Old Growth
  {"zone":"62","ranges":[[160,163]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 62::Silent Ascent
  {"zone":"63","ranges":[[42,60]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 63::Catacombs
  {"zone":"63","ranges":[[64,65],[67,70]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 63::Alongside the Iron Fence
  {"zone":"66","ranges":[[1,2],[4,9],[19,29]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 66::Prairie
  {"zone":"66","ranges":[[10,11],[30,30],[34,34],[36,36]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 66::Old Homestead
  {"zone":"66","ranges":[[14,18],[462,462]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 66::Wylder Spring
  {"zone":"66","ranges":[[388,401],[448,461]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 66::Nightshade Tangle
  {"zone":"66","ranges":[[555,559]],"arts":["/room-scenes/master-desert-trail.webp","/room-scenes/archetype-desert-1.webp","/room-scenes/archetype-desert-6.webp"]}, // 66::Sparkling Sands
  {"zone":"66","ranges":[[619,621],[635,635]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 66::Roadway
  {"zone":"66","ranges":[[622,633]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 66::Burned Fields
  {"zone":"66","ranges":[[636,636],[638,642]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 66::Sunbeam Circle
  {"zone":"67","ranges":[[2,9]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Diamond Street
  {"zone":"67","ranges":[[11,12],[14,15],[55,56],[58,59]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Yavash Circle
  {"zone":"67","ranges":[[17,25]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Ruby Street
  {"zone":"67","ranges":[[49,51],[53,54]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Opal Street
  {"zone":"67","ranges":[[60,65]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Crystal Lane
  {"zone":"67","ranges":[[72,73],[75,77]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Sapphire Avenue
  {"zone":"67","ranges":[[78,82],[84,85]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Moonstone Street
  {"zone":"67","ranges":[[86,87],[89,93]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Sunstone Street
  {"zone":"67","ranges":[[94,99]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Pearl Street
  {"zone":"67","ranges":[[106,110]],"arts":["/room-scenes/town-shard-master.webp"]}, // 67::Street of the Four Moons
  {"zone":"67","ranges":[[117,120]],"arts":["/room-scenes/master-garden.webp"]}, // 67::Garden Crescent
  {"zone":"67","ranges":[[319,325],[330,352]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 67::The Warrens
  {"zone":"67a","ranges":[[1,2],[13,15]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 67a::Tunnels
  {"zone":"68","ranges":[[103,106]],"arts":["/room-scenes/master-garden.webp"]}, // 68::Pyre Garden
  {"zone":"68","ranges":[[138,176],[209,210]],"arts":["/room-scenes/master-forest-path.webp"]}, // 68::Barrows
  {"zone":"68a","ranges":[[31,34]],"arts":["/room-scenes/master-forest-path.webp"]}, // 68a::Fissure
  {"zone":"69","ranges":[[59,60],[80,93],[96,99],[105,107],[114,115],[129,132]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 69::Grasslands
  {"zone":"69","ranges":[[455,456],[460,460],[467,467]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 69::Narrow Plateau
  {"zone":"69","ranges":[[465,466],[468,470]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 69::Waterfall Edge
  {"zone":"69","ranges":[[474,478]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 69::Above the Treeline
  {"zone":"69","ranges":[[480,486],[511,512]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 69::Breeding Grounds
  {"zone":"69","ranges":[[491,495]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 69::Highlands
  {"zone":"69","ranges":[[500,501],[506,506],[509,510]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 69::Snowcap
  {"zone":"69","ranges":[[575,579]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 69::Ridgeline Valley
  {"zone":"90","ranges":[[64,69]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Upper Mission Street
  {"zone":"90","ranges":[[70,74]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Lower Mission Street
  {"zone":"90","ranges":[[127,127],[130,134]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::East Eslan Street
  {"zone":"90","ranges":[[137,139],[141,145]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::West Eslan Street
  {"zone":"90","ranges":[[152,163]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Zeh'ra Boulevard
  {"zone":"90","ranges":[[203,204],[221,225]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Kor'adu Avenue
  {"zone":"90","ranges":[[412,412],[415,415],[429,429],[442,442]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Eastern Promenade
  {"zone":"90","ranges":[[446,446],[448,449],[456,456]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::East Regents Circle
  {"zone":"90","ranges":[[458,459],[479,480]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::West Regents Circle
  {"zone":"90","ranges":[[481,481],[512,514]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Western Promenade
  {"zone":"90","ranges":[[582,588]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Promenade East
  {"zone":"90","ranges":[[602,608]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Promenade West
  {"zone":"90","ranges":[[609,614]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Nadamian Avenue
  {"zone":"90","ranges":[[616,621]],"arts":["/room-scenes/town-ratha-master.webp"]}, // 90::Zsikiel Lane
  {"zone":"90","ranges":[[676,681]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 90::Eylhaar's Grotto
  {"zone":"90","ranges":[[692,695]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 90::Tunnels
  {"zone":"92","ranges":[[40,48]],"arts":["/room-scenes/master-open-grassland.webp"]}, // 92::Low Hills
  {"zone":"92","ranges":[[152,163]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 92::Itan Deep
  {"zone":"98","ranges":[[217,234],[279,279]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 98::Upper Caverns
  {"zone":"98","ranges":[[236,241]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 98::On the Column
  {"zone":"98","ranges":[[264,265],[268,270]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 98::Underground River
  {"zone":"98a","ranges":[[41,58],[95,95]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 98a::Upper Caverns
  {"zone":"98a","ranges":[[60,65]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 98a::On the Column
  {"zone":"98a","ranges":[[88,89],[92,93],[111,111]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 98a::Underground River
  {"zone":"98a","ranges":[[94,94],[100,108],[110,110]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 98a::Underwater
  {"zone":"99","ranges":[[23,24],[35,35],[119,119],[152,152],[160,160],[164,164],[395,395]],"arts":["/room-scenes/master-garden.webp"]}, // 99::Courtyard
  {"zone":"99","ranges":[[201,201],[210,210],[251,255],[257,257],[417,417]],"arts":["/room-scenes/master-garden.webp"]}, // 99::A Courtyard
  {"zone":"99","ranges":[[374,388]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 99::Necropolis Tunnels
  {"zone":"107","ranges":[[1,8]],"arts":["/room-scenes/master-garden.webp"]}, // 107::Garden
  {"zone":"107","ranges":[[196,198],[209,209],[230,230]],"arts":["/room-scenes/master-garden.webp"]}, // 107::Courtyard
  {"zone":"108","ranges":[[34,41],[43,45],[339,351]],"arts":["/room-scenes/master-desert-trail.webp","/room-scenes/archetype-desert-1.webp","/room-scenes/archetype-desert-6.webp"]}, // 108::Dunes
  {"zone":"108","ranges":[[230,233]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 108::The River Bank
  {"zone":"108","ranges":[[234,251]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 108::The Altanen River
  {"zone":"108","ranges":[[252,263]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 108::The Island
  {"zone":"108","ranges":[[384,402]],"arts":["/room-scenes/master-desert-trail.webp","/room-scenes/archetype-desert-1.webp","/room-scenes/archetype-desert-6.webp"]}, // 108::High Dunes
  {"zone":"108","ranges":[[437,441]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 108::Eastern Ascent
  {"zone":"112","ranges":[[172,183]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 112::Among the Trees
  {"zone":"116","ranges":[[57,59],[62,62],[67,67],[69,69],[74,74]],"arts":["/room-scenes/town-hibarnhvidar-master.webp"]}, // 116::Granite Street
  {"zone":"116","ranges":[[70,73]],"arts":["/room-scenes/town-hibarnhvidar-master.webp"]}, // 116::Pebble Lane
  {"zone":"116","ranges":[[346,350]],"arts":["/room-scenes/master-garden.webp"]}, // 116::Courtyard
  {"zone":"118e","ranges":[[1,14]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 118e::Stalagmite Maze
  {"zone":"123","ranges":[[236,241]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 123::Western Branch
  {"zone":"127","ranges":[[81,82],[84,84],[93,93],[96,96],[98,98],[100,100]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 127::Riverside
  {"zone":"127","ranges":[[140,162],[507,509],[511,522]],"arts":["/room-scenes/master-riverside.webp","/rooms/127-140.webp"]}, // 127::Liirewsag River
  {"zone":"127","ranges":[[164,214],[637,638],[641,642]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 127::Understory
  {"zone":"127","ranges":[[266,290]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 127::Blighted Tangle
  {"zone":"127","ranges":[[293,326],[352,352]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 127::Dark Burrows
  {"zone":"127","ranges":[[343,350]],"arts":["/room-scenes/master-deep-forest.webp"]}, // 127::Withered Foothills
  {"zone":"127","ranges":[[372,372],[374,375],[396,406],[408,418]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 127::Summit
  {"zone":"127","ranges":[[421,429],[431,432],[437,439],[441,449]],"arts":["/room-scenes/master-mine-tunnel.webp"]}, // 127::Frozen Tunnels
  {"zone":"150","ranges":[[269,272]],"arts":["/room-scenes/master-mountain-pass.webp","/room-scenes/curated-rain-grooved-outcrop.webp","/room-scenes/archetype-cliff-overlook-6.webp"]}, // 150::Verdant Outcrop
]

export function roomScenePattern(zone: string, room: number): string | null {
  for (const rule of RULES) {
    if (rule.zone !== zone) continue
    for (const [first, last] of rule.ranges) {
      if (room < first || room > last) continue
      const step = Math.floor((room - first) / HOLD_ROOMS)
      return rule.arts[step % rule.arts.length]
    }
  }
  return null
}
